### PR TITLE
Add GetVariableNames method to EquationCompiler (#2)

### PR DESCRIPTION
**Pull request by jmbledsoe**
I have a use case in which I need to list the variable names that were parsed in the equation. For now I'm resorting to reflection to extract them (for which I feel shame) so I'd like this supported by the library. Only added functionality so should be a minor update according to semantic versioning.

(This is the second attempt at the pull request, now including doc comments.)

### CODE REVIEW

**Comment by bcwood** [comment]
Excellent idea for another use case, thanks!

**Comment by jmbledsoe** [comment]
Will you please let me know when the NuGet package is updated? That way I can stop referencing my custom build.

**Comment by bcwood** [comment]
Yes I definitely will! I'm currently travelling for work (at Microsoft Ignite!), so it may be a few days. Thanks again for your contributions!

**Comment by bcwood** [comment]
@jmbledsoe the NuGet package has been updated with the latest changes.

**Pull request merged**
